name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Clean up old files
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        password: ${{ secrets.DROPLET_SSH_PASSWORD }}
        script: |
          rm -rf /var/www/fastapi-app/*

    - name: Copy files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        password: ${{ secrets.DROPLET_SSH_PASSWORD }}
        source: "."
        target: "/var/www/fastapi-app"

    - name: SSH and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        password: ${{ secrets.DROPLET_SSH_PASSWORD }}
        script: |
          cd /var/www/fastapi-app 
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart fastapi
